name: build, lint, test
on: 
  push:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        node: [17.x]
        os: [windows-2019, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps: 
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: install modules
        run: npm ci --force
      - name: build prod
        run: npm run build:prod
      - name: lint ts
        run: npm run lint
      - name: lint css
        run: npm run stylelint
      - name: unit test
        run: npm run test:unit
